#ifndef ARTEMIS_CONFIG_H
#define ARTEMIS_CONFIG_H

/* 循迹控制器模式：普通 PID 和模糊 PID 二选一。 */
#define ARTEMIS_LINE_PID_ORIGINAL 0
#define ARTEMIS_LINE_PID_FUZZY 1

#ifndef ARTEMIS_LINE_PID_MODE
#define ARTEMIS_LINE_PID_MODE ARTEMIS_LINE_PID_FUZZY
#endif

/* 仿真协议和任务基础参数。编码器 tick 通过这里换算为厘米。 */
#define ARTEMIS_ENCODER_TICKS_PER_CM 10.62f
#define ARTEMIS_START_MAX_TIME_S 120.0f
#define ARTEMIS_CONTROL_PERIOD_S 0.02f
#define ARTEMIS_INITIAL_PROGRESS_INDEX 0U

/* 握手阶段使用更短超时，桥接软件后启动时能更快等到下一条 START。 */
#define ARTEMIS_RESPONSE_TIMEOUT_MS 6000U
#define ARTEMIS_START_RESPONSE_TIMEOUT_MS 1000U
#define ARTEMIS_RETRY_DELAY_MS 1000U

/* 任务状态机里的黑线确认策略：见线 2 帧确认，循迹丢线 50 帧结束。 */
#define ARTEMIS_LINE_CONFIRM_FRAMES 2U
#define ARTEMIS_LINE_LOSS_FRAMES 50U

/* PA14 指示灯策略：黑线接触/离开边沿确认后闪烁。 */
#define ARTEMIS_LED_CONFIRM_FRAMES 2U
#define ARTEMIS_LED_ON_MS 500U
#define ARTEMIS_LED_GAP_MS 100U

/* 串口缓冲区。RX 环形缓冲必须是 2 的幂，便于用位运算回绕。 */
#define ARTEMIS_UART_RX_BUFFER_SIZE 512U
#define ARTEMIS_UART_LINE_BUFFER_SIZE 256U
#define ARTEMIS_UART_TX_BUFFER_SIZE 128U

#if (ARTEMIS_LINE_PID_MODE != ARTEMIS_LINE_PID_ORIGINAL) && \
    (ARTEMIS_LINE_PID_MODE != ARTEMIS_LINE_PID_FUZZY)
#error "ARTEMIS_LINE_PID_MODE must be ORIGINAL or FUZZY"
#endif

#endif
